import React from 'react'
import Head from 'next/head'

const Tittle = () => {
  return (
    <div>
        <Head>
        <title>Wellcome to Chespestgame.shop - Only for Gamers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32-32.png"/>
      </Head>
    </div>
  )
}

export default Tittle